#!/usr/bin/env ruby
# coding: utf-8

require 'thor'

class Bmi < Thor
  desc 'bmi','param: height, weight'
  def bmi(height = 0,weight = 0)
    bmi = #{weight} / (#{height}*#{height})
	puts bmi
	case bmi
	when bmi >= 40 
   		puts "=>肥満(4度)"
 	when bmi >= 35 && bmi < 40
   		puts "=>肥満(3度)"
 	when bmi >= 30 && bmi < 35
   		puts "=>肥満(2度)"
 	when bmi >= 25 && bmi < 30
   		puts "=>肥満(1度)"
 	when bmi >= 18 && bmi < 25
   		puts "=>普通体重"
 	else bmi < 18
   		puts "=>低体重"
	end
    end
end

Bmi.start(ARGV)
