#!/usr/bin/env ruby
# coding:utf-8

require 'thor'
class Bmi < Thor
desc 'bmi','パラメータ: height, weight'
def bmi(height = 0,weight = 0)
bmi = #{weight} / (#{height}*#{height})
puts bmi
case bmi
when bmi < 18 
puts "=>低体重"
when bmi >= 18 && bmi < 25
puts "=>普通体重"
when bmi >= 25 && bmi < 30
puts "=>肥満（１度）"
when bmi >= 30 && bmi < 35
puts "=>肥満（２度）"
when bmi >= 35 && bmi < 40
puts "=>肥満（３度）"
else bmi < 40
puts "=>肥満（４度）"
end
  end
    end
      
        Bmi.start(ARGV)

