#!/usr/bin/env ruby
# coding: utf-8

require 'thor'

class Wcex < Thor
  default_command :wcex
  desc 'wcex','file'
  option :file, :type => :string, :aliases => :f, desc: "name"
  def wcex
    input = File.open("#{options[:file]}")
    #input = File.open("./hoge.txt")
    l=0
    w=0
    c=0
    input.each_line do |line|
      l += 1
      c += line.size
      line.sub!(/^\s+/, "")
      ary = line.split
      w += ary.size
    end
    puts "[lines=#{l} words=#{w} chars=#{c}]"
  end
end
Wcex.start

